// flow-typed signature: 5304d5ac6ce4e6c40b4b6ab8291ba176
// flow-typed version: <<STUB>>/chart.js_v^3.2.1/flow_v0.150.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chart.js/auto/auto.esm' {
  declare module.exports: any;
}

declare module 'chart.js/auto/auto' {
  declare module.exports: any;
}

declare module 'chart.js/dist/chart.esm' {
  declare module.exports: any;
}

declare module 'chart.js/dist/chart' {
  declare module.exports: any;
}

declare module 'chart.js/dist/chart.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/chunks/helpers.segment' {
  declare module.exports: any;
}

declare module 'chart.js/dist/helpers.esm' {
  declare module.exports: any;
}

declare module 'chart.js/helpers/helpers.esm' {
  declare module.exports: any;
}

declare module 'chart.js/helpers/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chart.js/auto/auto.esm.js' {
  declare module.exports: $Exports<'chart.js/auto/auto.esm'>;
}
declare module 'chart.js/auto/auto.js' {
  declare module.exports: $Exports<'chart.js/auto/auto'>;
}
declare module 'chart.js/dist/chart.esm.js' {
  declare module.exports: $Exports<'chart.js/dist/chart.esm'>;
}
declare module 'chart.js/dist/chart.js' {
  declare module.exports: $Exports<'chart.js/dist/chart'>;
}
declare module 'chart.js/dist/chart.min.js' {
  declare module.exports: $Exports<'chart.js/dist/chart.min'>;
}
declare module 'chart.js/dist/chunks/helpers.segment.js' {
  declare module.exports: $Exports<'chart.js/dist/chunks/helpers.segment'>;
}
declare module 'chart.js/dist/helpers.esm.js' {
  declare module.exports: $Exports<'chart.js/dist/helpers.esm'>;
}
declare module 'chart.js/helpers/helpers.esm.js' {
  declare module.exports: $Exports<'chart.js/helpers/helpers.esm'>;
}
declare module 'chart.js/helpers/helpers.js' {
  declare module.exports: $Exports<'chart.js/helpers/helpers'>;
}
