// flow-typed signature: db913aced0dea5619e4b58100a8d2422
// flow-typed version: <<STUB>>/react-chartjs-2_v^3.0.3/flow_v0.150.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-chartjs-2/dist' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/dist/index.modern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-chartjs-2/dist/index' {
  declare module.exports: $Exports<'react-chartjs-2/dist'>;
}
declare module 'react-chartjs-2/dist/index.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist'>;
}
declare module 'react-chartjs-2/dist/index.modern.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist/index.modern'>;
}
