// flow-typed signature: d0f04b24c84815c97f7b0ea3b77b88fc
// flow-typed version: <<STUB>>/tailwindcss_vnpm:@tailwindcss/postcss7-compat@^2.1.2/flow_v0.150.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss/colors' {
  declare module.exports: any;
}

declare module 'tailwindcss/defaultConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/defaultTheme' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/accessibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/alignContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/alignItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/alignSelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/animation' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/appearance' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundAttachment' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundBlendMode' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundClip' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundImage' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundRepeat' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/backgroundSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderCollapse' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderRadius' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/borderWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/boxDecorationBreak' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/boxShadow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/boxSizing' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/clear' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/container' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/cursor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/display' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/divideColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/divideOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/divideStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/divideWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fill' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/flex' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/flexDirection' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/flexGrow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/flexShrink' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/flexWrap' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/float' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontFamily' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontSmoothing' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontVariantNumeric' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/fontWeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gap' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gradientColorStops' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridAutoColumns' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridAutoFlow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridAutoRows' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridColumn' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridColumnEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridColumnStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridRow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridRowEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridRowStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridTemplateColumns' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/gridTemplateRows' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/height' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/inset' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/isolation' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/justifyContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/justifyItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/justifySelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/letterSpacing' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/lineHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/listStylePosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/listStyleType' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/margin' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/maxHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/maxWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/minHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/minWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/mixBlendMode' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/objectFit' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/objectPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/opacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/order' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/outline' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/overflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/overscrollBehavior' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/padding' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/placeContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/placeholderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/placeholderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/placeItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/placeSelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/pointerEvents' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/position' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/preflight' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/resize' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/ringColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/ringOffsetColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/ringOffsetWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/ringOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/ringWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/rotate' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/scale' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/skew' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/space' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/stroke' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/strokeWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/tableLayout' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textDecoration' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textOverflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/textTransform' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transform' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transformOrigin' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transitionDelay' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transitionDuration' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transitionProperty' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/transitionTimingFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/translate' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/userSelect' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/verticalAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/visibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/whitespace' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/width' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/wordBreak' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/corePlugins/zIndex' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/collapseAdjacentRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/expandApplyAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/expandTailwindAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/generateRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/removeLayerAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/rewriteTailwindImports' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/setupContext' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/sharedState' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/lib/utils' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/pluginUtils' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/apply.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/arbitrary-values.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/basic-usage.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/collapse-adjacent-rules.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/context-reuse.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/context-reuse.worker' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/custom-extractors.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/custom-separator.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/import-syntax.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/important-boolean.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/important-modifier-prefix.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/important-modifier.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/important-selector.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/kitchen-sink.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/modify-selectors.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/mutable.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/prefix.fn.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/prefix.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/responsive-and-variants-atrules.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/svelte-syntax.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/jit/tests/variants.test' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/colors' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/help' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/init' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/compile' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/emoji' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/main' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/utils' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/constants' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/corePluginList' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/corePlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/featureFlags' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/index.postcss7' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/index.postcss8' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/applyImportantConfiguration' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/convertLayerAtRulesToControlComments' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/formatCSS' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/getModuleDependencies' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/purgeUnusedStyles' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/registerConfigAsDependency' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteScreenAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteTailwindAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteVariantsAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/accessibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/alignSelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/animation' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/appearance' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropBlur' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropBrightness' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropContrast' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropFilter' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropGrayscale' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropHueRotate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropInvert' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropSaturate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backdropSepia' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundAttachment' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundBlendMode' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundClip' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundImage' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundRepeat' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/backgroundSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/blur' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderCollapse' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderRadius' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/borderWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/boxDecorationBreak' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/boxShadow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/boxSizing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/brightness' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/clear' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/container' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/contrast' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/cursor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/display' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/divideWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/dropShadow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fill' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/filter' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flex' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexDirection' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexGrow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexShrink' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/flexWrap' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/float' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontFamily' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontSmoothing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontVariantNumeric' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/fontWeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gap' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gradientColorStops' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/grayscale' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridAutoColumns' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridAutoFlow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridAutoRows' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumn' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumnEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridColumnStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRowEnd' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridRowStart' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridTemplateColumns' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/gridTemplateRows' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/height' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/hueRotate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/inset' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/invert' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/isolation' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/justifyContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/justifyItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/justifySelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/letterSpacing' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/lineHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/listStylePosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/listStyleType' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/margin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/maxHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/maxWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/minHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/minWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/mixBlendMode' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/objectFit' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/objectPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/opacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/order' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/outline' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/overflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/overscrollBehavior' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/padding' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeContent' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeholderColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeholderOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeItems' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/placeSelf' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/pointerEvents' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/position' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/preflight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/resize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/ringColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/ringOffsetColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/ringOffsetWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/ringOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/ringWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/rotate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/saturate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/scale' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/sepia' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/skew' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/space' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/stroke' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/strokeWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/tableLayout' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textColor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textDecoration' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textOpacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textOverflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/textTransform' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transform' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transformOrigin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionDelay' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionDuration' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionProperty' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/transitionTimingFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/translate' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/userSelect' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/verticalAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/visibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/whitespace' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/width' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/wordBreak' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/zIndex' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/processTailwindFeatures' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildMediaQuery' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildSelectorVariant' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/cloneNodes' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/configurePlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/createPlugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/createUtilityPlugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/disposables' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/escapeClassName' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/flattenColorPalette' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/generateVariantFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/getAllConfigs' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/increaseSpecificity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/log' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/nameClass' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/negateValue' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/parseAnimationValue' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/parseObjectStyles' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixNegativeModifiers' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixSelector' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/processPlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/resolveConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/responsive' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/toColorValue' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/transformThemeValue' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/useMemo' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/usesCustomProperties' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/withAlphaVariable' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/wrapWithVariants' {
  declare module.exports: any;
}

declare module 'tailwindcss/plugin' {
  declare module.exports: any;
}

declare module 'tailwindcss/resolveConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/scripts/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/scripts/compat' {
  declare module.exports: any;
}

declare module 'tailwindcss/scripts/rebuildFixtures' {
  declare module.exports: any;
}

declare module 'tailwindcss/stubs/defaultConfig.stub' {
  declare module.exports: any;
}

declare module 'tailwindcss/stubs/defaultPostCssConfig.stub' {
  declare module.exports: any;
}

declare module 'tailwindcss/stubs/simpleConfig.stub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss/colors.js' {
  declare module.exports: $Exports<'tailwindcss/colors'>;
}
declare module 'tailwindcss/defaultConfig.js' {
  declare module.exports: $Exports<'tailwindcss/defaultConfig'>;
}
declare module 'tailwindcss/defaultTheme.js' {
  declare module.exports: $Exports<'tailwindcss/defaultTheme'>;
}
declare module 'tailwindcss/jit/corePlugins/accessibility.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/accessibility'>;
}
declare module 'tailwindcss/jit/corePlugins/alignContent.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/alignContent'>;
}
declare module 'tailwindcss/jit/corePlugins/alignItems.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/alignItems'>;
}
declare module 'tailwindcss/jit/corePlugins/alignSelf.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/alignSelf'>;
}
declare module 'tailwindcss/jit/corePlugins/animation.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/animation'>;
}
declare module 'tailwindcss/jit/corePlugins/appearance.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/appearance'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundAttachment.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundAttachment'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundBlendMode.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundBlendMode'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundClip.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundClip'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundColor'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundImage.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundImage'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundPosition.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundPosition'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundRepeat.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundRepeat'>;
}
declare module 'tailwindcss/jit/corePlugins/backgroundSize.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/backgroundSize'>;
}
declare module 'tailwindcss/jit/corePlugins/borderCollapse.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderCollapse'>;
}
declare module 'tailwindcss/jit/corePlugins/borderColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderColor'>;
}
declare module 'tailwindcss/jit/corePlugins/borderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/borderRadius.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderRadius'>;
}
declare module 'tailwindcss/jit/corePlugins/borderStyle.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderStyle'>;
}
declare module 'tailwindcss/jit/corePlugins/borderWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/borderWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/boxDecorationBreak.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/boxDecorationBreak'>;
}
declare module 'tailwindcss/jit/corePlugins/boxShadow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/boxShadow'>;
}
declare module 'tailwindcss/jit/corePlugins/boxSizing.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/boxSizing'>;
}
declare module 'tailwindcss/jit/corePlugins/clear.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/clear'>;
}
declare module 'tailwindcss/jit/corePlugins/container.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/container'>;
}
declare module 'tailwindcss/jit/corePlugins/cursor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/cursor'>;
}
declare module 'tailwindcss/jit/corePlugins/display.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/display'>;
}
declare module 'tailwindcss/jit/corePlugins/divideColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/divideColor'>;
}
declare module 'tailwindcss/jit/corePlugins/divideOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/divideOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/divideStyle.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/divideStyle'>;
}
declare module 'tailwindcss/jit/corePlugins/divideWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/divideWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/fill.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fill'>;
}
declare module 'tailwindcss/jit/corePlugins/flex.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/flex'>;
}
declare module 'tailwindcss/jit/corePlugins/flexDirection.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/flexDirection'>;
}
declare module 'tailwindcss/jit/corePlugins/flexGrow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/flexGrow'>;
}
declare module 'tailwindcss/jit/corePlugins/flexShrink.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/flexShrink'>;
}
declare module 'tailwindcss/jit/corePlugins/flexWrap.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/flexWrap'>;
}
declare module 'tailwindcss/jit/corePlugins/float.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/float'>;
}
declare module 'tailwindcss/jit/corePlugins/fontFamily.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontFamily'>;
}
declare module 'tailwindcss/jit/corePlugins/fontSize.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontSize'>;
}
declare module 'tailwindcss/jit/corePlugins/fontSmoothing.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontSmoothing'>;
}
declare module 'tailwindcss/jit/corePlugins/fontStyle.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontStyle'>;
}
declare module 'tailwindcss/jit/corePlugins/fontVariantNumeric.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontVariantNumeric'>;
}
declare module 'tailwindcss/jit/corePlugins/fontWeight.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/fontWeight'>;
}
declare module 'tailwindcss/jit/corePlugins/gap.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gap'>;
}
declare module 'tailwindcss/jit/corePlugins/gradientColorStops.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gradientColorStops'>;
}
declare module 'tailwindcss/jit/corePlugins/gridAutoColumns.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridAutoColumns'>;
}
declare module 'tailwindcss/jit/corePlugins/gridAutoFlow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridAutoFlow'>;
}
declare module 'tailwindcss/jit/corePlugins/gridAutoRows.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridAutoRows'>;
}
declare module 'tailwindcss/jit/corePlugins/gridColumn.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridColumn'>;
}
declare module 'tailwindcss/jit/corePlugins/gridColumnEnd.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridColumnEnd'>;
}
declare module 'tailwindcss/jit/corePlugins/gridColumnStart.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridColumnStart'>;
}
declare module 'tailwindcss/jit/corePlugins/gridRow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridRow'>;
}
declare module 'tailwindcss/jit/corePlugins/gridRowEnd.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridRowEnd'>;
}
declare module 'tailwindcss/jit/corePlugins/gridRowStart.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridRowStart'>;
}
declare module 'tailwindcss/jit/corePlugins/gridTemplateColumns.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridTemplateColumns'>;
}
declare module 'tailwindcss/jit/corePlugins/gridTemplateRows.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/gridTemplateRows'>;
}
declare module 'tailwindcss/jit/corePlugins/height.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/height'>;
}
declare module 'tailwindcss/jit/corePlugins/index' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins'>;
}
declare module 'tailwindcss/jit/corePlugins/index.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins'>;
}
declare module 'tailwindcss/jit/corePlugins/inset.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/inset'>;
}
declare module 'tailwindcss/jit/corePlugins/isolation.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/isolation'>;
}
declare module 'tailwindcss/jit/corePlugins/justifyContent.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/justifyContent'>;
}
declare module 'tailwindcss/jit/corePlugins/justifyItems.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/justifyItems'>;
}
declare module 'tailwindcss/jit/corePlugins/justifySelf.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/justifySelf'>;
}
declare module 'tailwindcss/jit/corePlugins/letterSpacing.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/letterSpacing'>;
}
declare module 'tailwindcss/jit/corePlugins/lineHeight.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/lineHeight'>;
}
declare module 'tailwindcss/jit/corePlugins/listStylePosition.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/listStylePosition'>;
}
declare module 'tailwindcss/jit/corePlugins/listStyleType.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/listStyleType'>;
}
declare module 'tailwindcss/jit/corePlugins/margin.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/margin'>;
}
declare module 'tailwindcss/jit/corePlugins/maxHeight.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/maxHeight'>;
}
declare module 'tailwindcss/jit/corePlugins/maxWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/maxWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/minHeight.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/minHeight'>;
}
declare module 'tailwindcss/jit/corePlugins/minWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/minWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/mixBlendMode.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/mixBlendMode'>;
}
declare module 'tailwindcss/jit/corePlugins/objectFit.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/objectFit'>;
}
declare module 'tailwindcss/jit/corePlugins/objectPosition.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/objectPosition'>;
}
declare module 'tailwindcss/jit/corePlugins/opacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/opacity'>;
}
declare module 'tailwindcss/jit/corePlugins/order.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/order'>;
}
declare module 'tailwindcss/jit/corePlugins/outline.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/outline'>;
}
declare module 'tailwindcss/jit/corePlugins/overflow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/overflow'>;
}
declare module 'tailwindcss/jit/corePlugins/overscrollBehavior.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/overscrollBehavior'>;
}
declare module 'tailwindcss/jit/corePlugins/padding.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/padding'>;
}
declare module 'tailwindcss/jit/corePlugins/placeContent.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/placeContent'>;
}
declare module 'tailwindcss/jit/corePlugins/placeholderColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/placeholderColor'>;
}
declare module 'tailwindcss/jit/corePlugins/placeholderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/placeholderOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/placeItems.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/placeItems'>;
}
declare module 'tailwindcss/jit/corePlugins/placeSelf.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/placeSelf'>;
}
declare module 'tailwindcss/jit/corePlugins/pointerEvents.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/pointerEvents'>;
}
declare module 'tailwindcss/jit/corePlugins/position.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/position'>;
}
declare module 'tailwindcss/jit/corePlugins/preflight.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/preflight'>;
}
declare module 'tailwindcss/jit/corePlugins/resize.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/resize'>;
}
declare module 'tailwindcss/jit/corePlugins/ringColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/ringColor'>;
}
declare module 'tailwindcss/jit/corePlugins/ringOffsetColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/ringOffsetColor'>;
}
declare module 'tailwindcss/jit/corePlugins/ringOffsetWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/ringOffsetWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/ringOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/ringOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/ringWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/ringWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/rotate.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/rotate'>;
}
declare module 'tailwindcss/jit/corePlugins/scale.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/scale'>;
}
declare module 'tailwindcss/jit/corePlugins/skew.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/skew'>;
}
declare module 'tailwindcss/jit/corePlugins/space.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/space'>;
}
declare module 'tailwindcss/jit/corePlugins/stroke.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/stroke'>;
}
declare module 'tailwindcss/jit/corePlugins/strokeWidth.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/strokeWidth'>;
}
declare module 'tailwindcss/jit/corePlugins/tableLayout.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/tableLayout'>;
}
declare module 'tailwindcss/jit/corePlugins/textAlign.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textAlign'>;
}
declare module 'tailwindcss/jit/corePlugins/textColor.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textColor'>;
}
declare module 'tailwindcss/jit/corePlugins/textDecoration.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textDecoration'>;
}
declare module 'tailwindcss/jit/corePlugins/textOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textOpacity'>;
}
declare module 'tailwindcss/jit/corePlugins/textOverflow.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textOverflow'>;
}
declare module 'tailwindcss/jit/corePlugins/textTransform.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/textTransform'>;
}
declare module 'tailwindcss/jit/corePlugins/transform.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transform'>;
}
declare module 'tailwindcss/jit/corePlugins/transformOrigin.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transformOrigin'>;
}
declare module 'tailwindcss/jit/corePlugins/transitionDelay.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transitionDelay'>;
}
declare module 'tailwindcss/jit/corePlugins/transitionDuration.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transitionDuration'>;
}
declare module 'tailwindcss/jit/corePlugins/transitionProperty.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transitionProperty'>;
}
declare module 'tailwindcss/jit/corePlugins/transitionTimingFunction.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/transitionTimingFunction'>;
}
declare module 'tailwindcss/jit/corePlugins/translate.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/translate'>;
}
declare module 'tailwindcss/jit/corePlugins/userSelect.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/userSelect'>;
}
declare module 'tailwindcss/jit/corePlugins/verticalAlign.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/verticalAlign'>;
}
declare module 'tailwindcss/jit/corePlugins/visibility.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/visibility'>;
}
declare module 'tailwindcss/jit/corePlugins/whitespace.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/whitespace'>;
}
declare module 'tailwindcss/jit/corePlugins/width.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/width'>;
}
declare module 'tailwindcss/jit/corePlugins/wordBreak.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/wordBreak'>;
}
declare module 'tailwindcss/jit/corePlugins/zIndex.js' {
  declare module.exports: $Exports<'tailwindcss/jit/corePlugins/zIndex'>;
}
declare module 'tailwindcss/jit/index' {
  declare module.exports: $Exports<'tailwindcss/jit'>;
}
declare module 'tailwindcss/jit/index.js' {
  declare module.exports: $Exports<'tailwindcss/jit'>;
}
declare module 'tailwindcss/jit/lib/collapseAdjacentRules.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/collapseAdjacentRules'>;
}
declare module 'tailwindcss/jit/lib/expandApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/expandApplyAtRules'>;
}
declare module 'tailwindcss/jit/lib/expandTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/expandTailwindAtRules'>;
}
declare module 'tailwindcss/jit/lib/generateRules.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/generateRules'>;
}
declare module 'tailwindcss/jit/lib/removeLayerAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/removeLayerAtRules'>;
}
declare module 'tailwindcss/jit/lib/rewriteTailwindImports.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/rewriteTailwindImports'>;
}
declare module 'tailwindcss/jit/lib/setupContext.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/setupContext'>;
}
declare module 'tailwindcss/jit/lib/sharedState.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/sharedState'>;
}
declare module 'tailwindcss/jit/lib/utils.js' {
  declare module.exports: $Exports<'tailwindcss/jit/lib/utils'>;
}
declare module 'tailwindcss/jit/pluginUtils.js' {
  declare module.exports: $Exports<'tailwindcss/jit/pluginUtils'>;
}
declare module 'tailwindcss/jit/tests/apply.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/apply.test'>;
}
declare module 'tailwindcss/jit/tests/arbitrary-values.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/arbitrary-values.test'>;
}
declare module 'tailwindcss/jit/tests/basic-usage.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/basic-usage.test'>;
}
declare module 'tailwindcss/jit/tests/collapse-adjacent-rules.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/collapse-adjacent-rules.test'>;
}
declare module 'tailwindcss/jit/tests/context-reuse.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/context-reuse.test'>;
}
declare module 'tailwindcss/jit/tests/context-reuse.worker.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/context-reuse.worker'>;
}
declare module 'tailwindcss/jit/tests/custom-extractors.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/custom-extractors.test'>;
}
declare module 'tailwindcss/jit/tests/custom-separator.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/custom-separator.test'>;
}
declare module 'tailwindcss/jit/tests/import-syntax.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/import-syntax.test'>;
}
declare module 'tailwindcss/jit/tests/important-boolean.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/important-boolean.test'>;
}
declare module 'tailwindcss/jit/tests/important-modifier-prefix.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/important-modifier-prefix.test'>;
}
declare module 'tailwindcss/jit/tests/important-modifier.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/important-modifier.test'>;
}
declare module 'tailwindcss/jit/tests/important-selector.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/important-selector.test'>;
}
declare module 'tailwindcss/jit/tests/kitchen-sink.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/kitchen-sink.test'>;
}
declare module 'tailwindcss/jit/tests/modify-selectors.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/modify-selectors.test'>;
}
declare module 'tailwindcss/jit/tests/mutable.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/mutable.test'>;
}
declare module 'tailwindcss/jit/tests/prefix.fn.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/prefix.fn.test'>;
}
declare module 'tailwindcss/jit/tests/prefix.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/prefix.test'>;
}
declare module 'tailwindcss/jit/tests/responsive-and-variants-atrules.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/responsive-and-variants-atrules.test'>;
}
declare module 'tailwindcss/jit/tests/svelte-syntax.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/svelte-syntax.test'>;
}
declare module 'tailwindcss/jit/tests/variants.test.js' {
  declare module.exports: $Exports<'tailwindcss/jit/tests/variants.test'>;
}
declare module 'tailwindcss/lib/cli.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli'>;
}
declare module 'tailwindcss/lib/cli/colors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/colors'>;
}
declare module 'tailwindcss/lib/cli/commands/build.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/build'>;
}
declare module 'tailwindcss/lib/cli/commands/help.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/help'>;
}
declare module 'tailwindcss/lib/cli/commands/index' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands'>;
}
declare module 'tailwindcss/lib/cli/commands/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands'>;
}
declare module 'tailwindcss/lib/cli/commands/init.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/init'>;
}
declare module 'tailwindcss/lib/cli/compile.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/compile'>;
}
declare module 'tailwindcss/lib/cli/emoji.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/emoji'>;
}
declare module 'tailwindcss/lib/cli/main.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/main'>;
}
declare module 'tailwindcss/lib/cli/utils.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/utils'>;
}
declare module 'tailwindcss/lib/constants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/constants'>;
}
declare module 'tailwindcss/lib/corePluginList.js' {
  declare module.exports: $Exports<'tailwindcss/lib/corePluginList'>;
}
declare module 'tailwindcss/lib/corePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/corePlugins'>;
}
declare module 'tailwindcss/lib/featureFlags.js' {
  declare module.exports: $Exports<'tailwindcss/lib/featureFlags'>;
}
declare module 'tailwindcss/lib/index' {
  declare module.exports: $Exports<'tailwindcss/lib'>;
}
declare module 'tailwindcss/lib/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib'>;
}
declare module 'tailwindcss/lib/index.postcss7.js' {
  declare module.exports: $Exports<'tailwindcss/lib/index.postcss7'>;
}
declare module 'tailwindcss/lib/index.postcss8.js' {
  declare module.exports: $Exports<'tailwindcss/lib/index.postcss8'>;
}
declare module 'tailwindcss/lib/lib/applyImportantConfiguration.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/applyImportantConfiguration'>;
}
declare module 'tailwindcss/lib/lib/convertLayerAtRulesToControlComments.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/convertLayerAtRulesToControlComments'>;
}
declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/evaluateTailwindFunctions'>;
}
declare module 'tailwindcss/lib/lib/formatCSS.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/formatCSS'>;
}
declare module 'tailwindcss/lib/lib/getModuleDependencies.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/getModuleDependencies'>;
}
declare module 'tailwindcss/lib/lib/purgeUnusedStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/purgeUnusedStyles'>;
}
declare module 'tailwindcss/lib/lib/registerConfigAsDependency.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/registerConfigAsDependency'>;
}
declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteClassApplyAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteResponsiveAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteScreenAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteScreenAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteTailwindAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteVariantsAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteVariantsAtRules'>;
}
declare module 'tailwindcss/lib/plugins/accessibility.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/accessibility'>;
}
declare module 'tailwindcss/lib/plugins/alignContent.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignContent'>;
}
declare module 'tailwindcss/lib/plugins/alignItems.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignItems'>;
}
declare module 'tailwindcss/lib/plugins/alignSelf.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/alignSelf'>;
}
declare module 'tailwindcss/lib/plugins/animation.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/animation'>;
}
declare module 'tailwindcss/lib/plugins/appearance.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/appearance'>;
}
declare module 'tailwindcss/lib/plugins/backdropBlur.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropBlur'>;
}
declare module 'tailwindcss/lib/plugins/backdropBrightness.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropBrightness'>;
}
declare module 'tailwindcss/lib/plugins/backdropContrast.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropContrast'>;
}
declare module 'tailwindcss/lib/plugins/backdropFilter.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropFilter'>;
}
declare module 'tailwindcss/lib/plugins/backdropGrayscale.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropGrayscale'>;
}
declare module 'tailwindcss/lib/plugins/backdropHueRotate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropHueRotate'>;
}
declare module 'tailwindcss/lib/plugins/backdropInvert.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropInvert'>;
}
declare module 'tailwindcss/lib/plugins/backdropOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropOpacity'>;
}
declare module 'tailwindcss/lib/plugins/backdropSaturate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropSaturate'>;
}
declare module 'tailwindcss/lib/plugins/backdropSepia.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backdropSepia'>;
}
declare module 'tailwindcss/lib/plugins/backgroundAttachment.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundAttachment'>;
}
declare module 'tailwindcss/lib/plugins/backgroundBlendMode.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundBlendMode'>;
}
declare module 'tailwindcss/lib/plugins/backgroundClip.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundClip'>;
}
declare module 'tailwindcss/lib/plugins/backgroundColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundColor'>;
}
declare module 'tailwindcss/lib/plugins/backgroundImage.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundImage'>;
}
declare module 'tailwindcss/lib/plugins/backgroundOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundOpacity'>;
}
declare module 'tailwindcss/lib/plugins/backgroundPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundPosition'>;
}
declare module 'tailwindcss/lib/plugins/backgroundRepeat.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundRepeat'>;
}
declare module 'tailwindcss/lib/plugins/backgroundSize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/backgroundSize'>;
}
declare module 'tailwindcss/lib/plugins/blur.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/blur'>;
}
declare module 'tailwindcss/lib/plugins/borderCollapse.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderCollapse'>;
}
declare module 'tailwindcss/lib/plugins/borderColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderColor'>;
}
declare module 'tailwindcss/lib/plugins/borderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderOpacity'>;
}
declare module 'tailwindcss/lib/plugins/borderRadius.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderRadius'>;
}
declare module 'tailwindcss/lib/plugins/borderStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderStyle'>;
}
declare module 'tailwindcss/lib/plugins/borderWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/borderWidth'>;
}
declare module 'tailwindcss/lib/plugins/boxDecorationBreak.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/boxDecorationBreak'>;
}
declare module 'tailwindcss/lib/plugins/boxShadow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/boxShadow'>;
}
declare module 'tailwindcss/lib/plugins/boxSizing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/boxSizing'>;
}
declare module 'tailwindcss/lib/plugins/brightness.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/brightness'>;
}
declare module 'tailwindcss/lib/plugins/clear.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/clear'>;
}
declare module 'tailwindcss/lib/plugins/container.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/container'>;
}
declare module 'tailwindcss/lib/plugins/contrast.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/contrast'>;
}
declare module 'tailwindcss/lib/plugins/cursor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/cursor'>;
}
declare module 'tailwindcss/lib/plugins/display.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/display'>;
}
declare module 'tailwindcss/lib/plugins/divideColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideColor'>;
}
declare module 'tailwindcss/lib/plugins/divideOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideOpacity'>;
}
declare module 'tailwindcss/lib/plugins/divideStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideStyle'>;
}
declare module 'tailwindcss/lib/plugins/divideWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/divideWidth'>;
}
declare module 'tailwindcss/lib/plugins/dropShadow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/dropShadow'>;
}
declare module 'tailwindcss/lib/plugins/fill.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fill'>;
}
declare module 'tailwindcss/lib/plugins/filter.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/filter'>;
}
declare module 'tailwindcss/lib/plugins/flex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flex'>;
}
declare module 'tailwindcss/lib/plugins/flexDirection.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexDirection'>;
}
declare module 'tailwindcss/lib/plugins/flexGrow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexGrow'>;
}
declare module 'tailwindcss/lib/plugins/flexShrink.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexShrink'>;
}
declare module 'tailwindcss/lib/plugins/flexWrap.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/flexWrap'>;
}
declare module 'tailwindcss/lib/plugins/float.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/float'>;
}
declare module 'tailwindcss/lib/plugins/fontFamily.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontFamily'>;
}
declare module 'tailwindcss/lib/plugins/fontSize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontSize'>;
}
declare module 'tailwindcss/lib/plugins/fontSmoothing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontSmoothing'>;
}
declare module 'tailwindcss/lib/plugins/fontStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontStyle'>;
}
declare module 'tailwindcss/lib/plugins/fontVariantNumeric.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontVariantNumeric'>;
}
declare module 'tailwindcss/lib/plugins/fontWeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/fontWeight'>;
}
declare module 'tailwindcss/lib/plugins/gap.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gap'>;
}
declare module 'tailwindcss/lib/plugins/gradientColorStops.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gradientColorStops'>;
}
declare module 'tailwindcss/lib/plugins/grayscale.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/grayscale'>;
}
declare module 'tailwindcss/lib/plugins/gridAutoColumns.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridAutoColumns'>;
}
declare module 'tailwindcss/lib/plugins/gridAutoFlow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridAutoFlow'>;
}
declare module 'tailwindcss/lib/plugins/gridAutoRows.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridAutoRows'>;
}
declare module 'tailwindcss/lib/plugins/gridColumn.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumn'>;
}
declare module 'tailwindcss/lib/plugins/gridColumnEnd.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumnEnd'>;
}
declare module 'tailwindcss/lib/plugins/gridColumnStart.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridColumnStart'>;
}
declare module 'tailwindcss/lib/plugins/gridRow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRow'>;
}
declare module 'tailwindcss/lib/plugins/gridRowEnd.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRowEnd'>;
}
declare module 'tailwindcss/lib/plugins/gridRowStart.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridRowStart'>;
}
declare module 'tailwindcss/lib/plugins/gridTemplateColumns.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridTemplateColumns'>;
}
declare module 'tailwindcss/lib/plugins/gridTemplateRows.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/gridTemplateRows'>;
}
declare module 'tailwindcss/lib/plugins/height.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/height'>;
}
declare module 'tailwindcss/lib/plugins/hueRotate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/hueRotate'>;
}
declare module 'tailwindcss/lib/plugins/index' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins'>;
}
declare module 'tailwindcss/lib/plugins/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins'>;
}
declare module 'tailwindcss/lib/plugins/inset.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/inset'>;
}
declare module 'tailwindcss/lib/plugins/invert.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/invert'>;
}
declare module 'tailwindcss/lib/plugins/isolation.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/isolation'>;
}
declare module 'tailwindcss/lib/plugins/justifyContent.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/justifyContent'>;
}
declare module 'tailwindcss/lib/plugins/justifyItems.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/justifyItems'>;
}
declare module 'tailwindcss/lib/plugins/justifySelf.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/justifySelf'>;
}
declare module 'tailwindcss/lib/plugins/letterSpacing.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/letterSpacing'>;
}
declare module 'tailwindcss/lib/plugins/lineHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/lineHeight'>;
}
declare module 'tailwindcss/lib/plugins/listStylePosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/listStylePosition'>;
}
declare module 'tailwindcss/lib/plugins/listStyleType.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/listStyleType'>;
}
declare module 'tailwindcss/lib/plugins/margin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/margin'>;
}
declare module 'tailwindcss/lib/plugins/maxHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/maxHeight'>;
}
declare module 'tailwindcss/lib/plugins/maxWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/maxWidth'>;
}
declare module 'tailwindcss/lib/plugins/minHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/minHeight'>;
}
declare module 'tailwindcss/lib/plugins/minWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/minWidth'>;
}
declare module 'tailwindcss/lib/plugins/mixBlendMode.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/mixBlendMode'>;
}
declare module 'tailwindcss/lib/plugins/objectFit.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/objectFit'>;
}
declare module 'tailwindcss/lib/plugins/objectPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/objectPosition'>;
}
declare module 'tailwindcss/lib/plugins/opacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/opacity'>;
}
declare module 'tailwindcss/lib/plugins/order.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/order'>;
}
declare module 'tailwindcss/lib/plugins/outline.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/outline'>;
}
declare module 'tailwindcss/lib/plugins/overflow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/overflow'>;
}
declare module 'tailwindcss/lib/plugins/overscrollBehavior.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/overscrollBehavior'>;
}
declare module 'tailwindcss/lib/plugins/padding.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/padding'>;
}
declare module 'tailwindcss/lib/plugins/placeContent.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeContent'>;
}
declare module 'tailwindcss/lib/plugins/placeholderColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeholderColor'>;
}
declare module 'tailwindcss/lib/plugins/placeholderOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeholderOpacity'>;
}
declare module 'tailwindcss/lib/plugins/placeItems.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeItems'>;
}
declare module 'tailwindcss/lib/plugins/placeSelf.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/placeSelf'>;
}
declare module 'tailwindcss/lib/plugins/pointerEvents.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/pointerEvents'>;
}
declare module 'tailwindcss/lib/plugins/position.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/position'>;
}
declare module 'tailwindcss/lib/plugins/preflight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/preflight'>;
}
declare module 'tailwindcss/lib/plugins/resize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/resize'>;
}
declare module 'tailwindcss/lib/plugins/ringColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/ringColor'>;
}
declare module 'tailwindcss/lib/plugins/ringOffsetColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/ringOffsetColor'>;
}
declare module 'tailwindcss/lib/plugins/ringOffsetWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/ringOffsetWidth'>;
}
declare module 'tailwindcss/lib/plugins/ringOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/ringOpacity'>;
}
declare module 'tailwindcss/lib/plugins/ringWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/ringWidth'>;
}
declare module 'tailwindcss/lib/plugins/rotate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/rotate'>;
}
declare module 'tailwindcss/lib/plugins/saturate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/saturate'>;
}
declare module 'tailwindcss/lib/plugins/scale.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/scale'>;
}
declare module 'tailwindcss/lib/plugins/sepia.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/sepia'>;
}
declare module 'tailwindcss/lib/plugins/skew.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/skew'>;
}
declare module 'tailwindcss/lib/plugins/space.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/space'>;
}
declare module 'tailwindcss/lib/plugins/stroke.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/stroke'>;
}
declare module 'tailwindcss/lib/plugins/strokeWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/strokeWidth'>;
}
declare module 'tailwindcss/lib/plugins/tableLayout.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/tableLayout'>;
}
declare module 'tailwindcss/lib/plugins/textAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textAlign'>;
}
declare module 'tailwindcss/lib/plugins/textColor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textColor'>;
}
declare module 'tailwindcss/lib/plugins/textDecoration.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textDecoration'>;
}
declare module 'tailwindcss/lib/plugins/textOpacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textOpacity'>;
}
declare module 'tailwindcss/lib/plugins/textOverflow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textOverflow'>;
}
declare module 'tailwindcss/lib/plugins/textTransform.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/textTransform'>;
}
declare module 'tailwindcss/lib/plugins/transform.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transform'>;
}
declare module 'tailwindcss/lib/plugins/transformOrigin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transformOrigin'>;
}
declare module 'tailwindcss/lib/plugins/transitionDelay.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionDelay'>;
}
declare module 'tailwindcss/lib/plugins/transitionDuration.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionDuration'>;
}
declare module 'tailwindcss/lib/plugins/transitionProperty.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionProperty'>;
}
declare module 'tailwindcss/lib/plugins/transitionTimingFunction.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/transitionTimingFunction'>;
}
declare module 'tailwindcss/lib/plugins/translate.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/translate'>;
}
declare module 'tailwindcss/lib/plugins/userSelect.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/userSelect'>;
}
declare module 'tailwindcss/lib/plugins/verticalAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/verticalAlign'>;
}
declare module 'tailwindcss/lib/plugins/visibility.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/visibility'>;
}
declare module 'tailwindcss/lib/plugins/whitespace.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/whitespace'>;
}
declare module 'tailwindcss/lib/plugins/width.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/width'>;
}
declare module 'tailwindcss/lib/plugins/wordBreak.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/wordBreak'>;
}
declare module 'tailwindcss/lib/plugins/zIndex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/zIndex'>;
}
declare module 'tailwindcss/lib/processTailwindFeatures.js' {
  declare module.exports: $Exports<'tailwindcss/lib/processTailwindFeatures'>;
}
declare module 'tailwindcss/lib/util/buildMediaQuery.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildMediaQuery'>;
}
declare module 'tailwindcss/lib/util/buildSelectorVariant.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildSelectorVariant'>;
}
declare module 'tailwindcss/lib/util/cloneNodes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/cloneNodes'>;
}
declare module 'tailwindcss/lib/util/configurePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/configurePlugins'>;
}
declare module 'tailwindcss/lib/util/createPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createPlugin'>;
}
declare module 'tailwindcss/lib/util/createUtilityPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createUtilityPlugin'>;
}
declare module 'tailwindcss/lib/util/disposables.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/disposables'>;
}
declare module 'tailwindcss/lib/util/escapeClassName.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/escapeClassName'>;
}
declare module 'tailwindcss/lib/util/flattenColorPalette.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/flattenColorPalette'>;
}
declare module 'tailwindcss/lib/util/generateVariantFunction.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/generateVariantFunction'>;
}
declare module 'tailwindcss/lib/util/getAllConfigs.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/getAllConfigs'>;
}
declare module 'tailwindcss/lib/util/increaseSpecificity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/increaseSpecificity'>;
}
declare module 'tailwindcss/lib/util/log.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/log'>;
}
declare module 'tailwindcss/lib/util/nameClass.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/nameClass'>;
}
declare module 'tailwindcss/lib/util/negateValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/negateValue'>;
}
declare module 'tailwindcss/lib/util/parseAnimationValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseAnimationValue'>;
}
declare module 'tailwindcss/lib/util/parseObjectStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseObjectStyles'>;
}
declare module 'tailwindcss/lib/util/prefixNegativeModifiers.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixNegativeModifiers'>;
}
declare module 'tailwindcss/lib/util/prefixSelector.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixSelector'>;
}
declare module 'tailwindcss/lib/util/processPlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/processPlugins'>;
}
declare module 'tailwindcss/lib/util/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/resolveConfig'>;
}
declare module 'tailwindcss/lib/util/responsive.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/responsive'>;
}
declare module 'tailwindcss/lib/util/toColorValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/toColorValue'>;
}
declare module 'tailwindcss/lib/util/transformThemeValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/transformThemeValue'>;
}
declare module 'tailwindcss/lib/util/useMemo.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/useMemo'>;
}
declare module 'tailwindcss/lib/util/usesCustomProperties.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/usesCustomProperties'>;
}
declare module 'tailwindcss/lib/util/withAlphaVariable.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/withAlphaVariable'>;
}
declare module 'tailwindcss/lib/util/wrapWithVariants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/wrapWithVariants'>;
}
declare module 'tailwindcss/plugin.js' {
  declare module.exports: $Exports<'tailwindcss/plugin'>;
}
declare module 'tailwindcss/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/resolveConfig'>;
}
declare module 'tailwindcss/scripts/build.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/build'>;
}
declare module 'tailwindcss/scripts/compat.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/compat'>;
}
declare module 'tailwindcss/scripts/rebuildFixtures.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/rebuildFixtures'>;
}
declare module 'tailwindcss/stubs/defaultConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/defaultConfig.stub'>;
}
declare module 'tailwindcss/stubs/defaultPostCssConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/defaultPostCssConfig.stub'>;
}
declare module 'tailwindcss/stubs/simpleConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/simpleConfig.stub'>;
}
