// flow-typed signature: 8097c904734a9f31aef7f4a082f8bd4c
// flow-typed version: <<STUB>>/@googlemaps/js-api-loader_v^1.11.4/flow_v0.150.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@googlemaps/js-api-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@googlemaps/js-api-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@googlemaps/js-api-loader/dist/index.dev' {
  declare module.exports: any;
}

declare module '@googlemaps/js-api-loader/dist/index.esm' {
  declare module.exports: any;
}

declare module '@googlemaps/js-api-loader/dist/index.min' {
  declare module.exports: any;
}

declare module '@googlemaps/js-api-loader/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@googlemaps/js-api-loader/dist/index.dev.js' {
  declare module.exports: $Exports<'@googlemaps/js-api-loader/dist/index.dev'>;
}
declare module '@googlemaps/js-api-loader/dist/index.esm.js' {
  declare module.exports: $Exports<'@googlemaps/js-api-loader/dist/index.esm'>;
}
declare module '@googlemaps/js-api-loader/dist/index.min.js' {
  declare module.exports: $Exports<'@googlemaps/js-api-loader/dist/index.min'>;
}
declare module '@googlemaps/js-api-loader/dist/index.umd.js' {
  declare module.exports: $Exports<'@googlemaps/js-api-loader/dist/index.umd'>;
}
