// flow-typed signature: f66222c386908e66bd8a9e47f74f0295
// flow-typed version: <<STUB>>/@tailwindcss/forms_v^0.3.2/flow_v0.150.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tailwindcss/forms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tailwindcss/forms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tailwindcss/forms/scripts/build' {
  declare module.exports: any;
}

declare module '@tailwindcss/forms/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tailwindcss/forms/scripts/build.js' {
  declare module.exports: $Exports<'@tailwindcss/forms/scripts/build'>;
}
declare module '@tailwindcss/forms/src/index' {
  declare module.exports: $Exports<'@tailwindcss/forms/src'>;
}
declare module '@tailwindcss/forms/src/index.js' {
  declare module.exports: $Exports<'@tailwindcss/forms/src'>;
}
